# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file and should be
# only used for development purpose.
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.redhat.parodos.notification: DEBUG

spring:
  jackson:
    serialization:
      indent-output: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak_url:http://localhost:3434/realms/Parodos/protocol/openid-connect/certs}
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:h2:mem:notification_service
    driverClassName: org.h2.Driver
    username: postgres
    password: postgres

server:
  port: ${SERVER_PORT:8088}

# ===================================================================
# Application specific properties
# Add your own application properties here, see the
# ApplicationProperties class to have type-safe configuration
# ===================================================================

